/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
  


    public static void main(String[] args) {
        
       /* ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setName("Projeto Teste ");
        project.setDescription("description");
        projectController.save(project);
        
        project.setId(2);
        project.setName("Novo nome do projeto");
        projectController.update(project);
        
        
        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de project = " + projects.size());
        
        projectController.removeById(1);
       
        TaskController taskController = new TaskController();
        
        Task task = new Task();
        
        task.setIdProject(2);
        task.setName("limpar a casa");
        task.setDescription("limpar todos os  banheiros");
        task.setCompleted(true);
        
        taskController.save(task);
        
        task.setId(2);
        task.setName("Lavar o carro");
        task.setCompleted(false);
        taskController.update(task);
       
       taskController.removeById(3);
       
       List<Task> tasks = taskController.getAll(2);
        System.out.println("O total de tarefas no projeto " + task.getIdProject() + "é: " + tasks.size());
        
        */
    }
}
